### ISSUE TITLE
Inserting Formatted Text

### ISSUE THREAD

**Issue by blazetoday** [matthewsot/docs-plus#1]
Is it possible to use this to insert formatted text.

E.g. having

"this is \<b>bold\</b>"

would insert

this is **bold**

**Comment by matthewsot** [comment]
Yes - it should definitely be possible! Though you might have to write in some extra code.

A good template would be the docs.toggleSubscript() implementation here: https://github.com/matthewsot/docs-plus/blob/master/docs.js#L163

You'll want to change that so that instead of pressing ctrl + comma it presses ctrl + b, and then your insertion code would look something like:

```
docs.insertText("this is");
docs.toggleBold();
docs.insertText("bold")
docs.toggleBold();
```

(potentially with a few timeouts to give the editor time to realize the bold toggle, but that's something you would have to experiment with).

Feel free to add the toggleBold function, otherwise I should be able to write/test one out next weekend :)

Thanks!
Matthew

**Comment by matthewsot** [comment]
Hello,

I've added a toggleBold function as of https://github.com/matthewsot/docs-plus/commit/45e3006e8b5a99a965cd16bd35e8a47202c1124f

I also fixed a few bugs with the insertText implementation - it should all work on Chrome now!

The test code that works for me:

```
docs.toggleBold();
docs.insertText("hi");
docs.toggleBold();
docs.insertText("hi");
docs.toggleSubscript();
docs.insertText("hi");
docs.toggleSubscript();
docs.insertText("hi");
```

Results:
![image](https://cloud.githubusercontent.com/assets/1159057/26278301/ecd1eb2a-3d4b-11e7-8283-4552c82a0e6f.png)

Let me know if you have further issues with it and we can definitely re-open this issue (or create a new one) to resolve them.

Thanks,
Matthew
